### ISSUE TITLE
cannot find module '../lib/extras/promise'

### ISSUE THREAD

**Issue by schamp** [nolanlawson/pouchdb-full-sync#2]
I just ran an install:

`$ npm install pouchdb-full-sync`

and added it to my script:

```
var PouchDB = require('PouchDB')
PouchDB.plugin(require('pouchdb-full-sync'))
```
per the instructions, but I get:
```
module.js:341
    throw err;
    ^

Error: Cannot find module '../lib/extras/promise'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/aschamp/iped-api/node_modules/pouchdb-full-sync/node_modules/pouchdb/extras/promise.js:4:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by nolanlawson** [comment]
My bad, this is a change in PouchDB 5.2.0 that I need to fix. It should be `pouchdb/extras/promise`.

**Comment by nolanlawson** [comment]
Er no wait, the bug is that I need to change the PouchDB dependency to 5.2.1 instead of pouchdb/pouchdb.
